# Form implementation generated from reading ui file 'fuzzy.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from app.views.editor_tab_view import EditorTabWidget
from app.views.central_tab_view import CentralTabWidget
from app.views.browser_frame_view import BrowserFrameWidget
from app.views.top_menu_view import TopMenu
from app.views.bar_menu_view import BarMenuWidget


def retranslateUi(MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


class UiMainWindow(object):
    def __init__(self):
        self.editorTab = None
        self.upMenuTab = None
        self.browserFrame = None
        self.plotTabs = None
        self.statusBar = None
        self.menuBar = None

    def setupUi(self, MainWindow):
        """Sets up the main window of application. All of the specific widgets are initiated via seperate classes."""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 780)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusBar)
        self.statusBar.showMessage("Started application")

        self.plotTabs = CentralTabWidget(parent=self.centralwidget, status_bar=self.statusBar)
        self.plotTabs.setGeometry(QtCore.QRect(310, 160, 531, 601))

        self.browserFrame = BrowserFrameWidget(parent=self.centralwidget, status_bar=self.statusBar)
        self.browserFrame.setGeometry(QtCore.QRect(0, 160, 301, 641))

        self.upMenuTab = TopMenu(parent=self.centralwidget, status_bar=self.statusBar)
        self.upMenuTab.setGeometry(QtCore.QRect(0, 0, 1081, 161))

        self.editorTab = EditorTabWidget(parent=self.centralwidget, status_bar=self.statusBar)
        self.editorTab.setGeometry(QtCore.QRect(820, 160, 281, 641))

        MainWindow.setCentralWidget(self.centralwidget)

        self.menuBar = BarMenuWidget(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1096, 26))

        retranslateUi(MainWindow)

        """Sets up the default tabs of tab widgets."""
        self.plotTabs.setCurrentIndex(0)
        self.upMenuTab.setCurrentIndex(0)
        self.editorTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
