# Form implementation generated from reading ui file 'fuzzy.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets

from app.views.browser_frame_view import BrowserFrameWidget
from app.views.central_tab_view import CentralTabWidget
from app.views.editor_tab_view import EditorTabWidget
from app.views.top_menu_view import TopMenu


class UiMainWindow(object):
    """UI Main Window class generated from Qt Designer."""

    def setupUi(self, MainWindow):
        """Set up the UI for the main window."""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 830)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.plotTabs = CentralTabWidget(parent=self.centralwidget)
        self.plotTabs.setGeometry(QtCore.QRect(310, 160, 531, 641))

        self.browserFrame = BrowserFrameWidget(parent=self.centralwidget)
        self.browserFrame.setGeometry(QtCore.QRect(0, 160, 301, 641))

        self.upMenuTab = TopMenu(parent=self.centralwidget)
        self.upMenuTab.setGeometry(QtCore.QRect(0, 0, 1081, 161))

        self.editorTab = EditorTabWidget(parent=self.centralwidget)
        self.editorTab.setGeometry(QtCore.QRect(820, 160, 281, 641))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.plotTabs.setCurrentIndex(2)
        self.upMenuTab.setCurrentIndex(0)
        self.editorTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """Retranslate the UI text."""
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
